"""empty message

Revision ID: bfea36a331b5
Revises: 
Create Date: 2024-06-18 10:04:13.934937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfea36a331b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admindetails',
    sa.Column('USER_ID', sa.String(length=30), nullable=False),
    sa.Column('EFFECTIVE_START_DATE', sa.DateTime(), nullable=False),
    sa.Column('EFFECTIVE_END_DATE', sa.DateTime(), nullable=False),
    sa.Column('FIRST_NAME', sa.String(length=150), nullable=False),
    sa.Column('MIDDLE_NAME', sa.String(length=150), nullable=True),
    sa.Column('LAST_NAME', sa.String(length=150), nullable=True),
    sa.Column('EMAIL_ID', sa.String(length=150), nullable=False),
    sa.Column('PASSWORD', sa.String(length=100), nullable=False),
    sa.Column('MOBILE_NUMBER', sa.String(length=150), nullable=True),
    sa.Column('ROLE', sa.String(length=150), nullable=False),
    sa.Column('CREATED_BY', sa.String(length=150), nullable=True),
    sa.Column('LAST_UPDATED_BY', sa.String(length=150), nullable=True),
    sa.Column('CREATION_DATE', sa.DateTime(), nullable=True),
    sa.Column('LAST_UPDATED_DATE', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('USER_ID', 'EFFECTIVE_START_DATE', 'EFFECTIVE_END_DATE'),
    sa.UniqueConstraint('EMAIL_ID')
    )
    op.create_table('templates',
    sa.Column('TEMPLATE_ID', sa.String(length=15), nullable=False),
    sa.Column('TEMPLATE_NAME', sa.String(length=150), nullable=False),
    sa.Column('TEMPLATE', sa.LargeBinary(length=20971520), nullable=True),
    sa.Column('TEMPLATE_SIZE', sa.Integer(), nullable=True),
    sa.Column('TEMPLATE_TYPE', sa.String(length=150), nullable=True),
    sa.Column('CREATED_BY', sa.String(length=150), nullable=True),
    sa.Column('LAST_UPDATED_BY', sa.String(length=150), nullable=True),
    sa.Column('CREATION_DATE', sa.DateTime(), nullable=True),
    sa.Column('LAST_UPDATED_DATE', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('TEMPLATE_ID')
    )
    op.create_table('employeedetails',
    sa.Column('EMPLOYEE_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EMPLOYEE_NUMBER', sa.String(length=15), nullable=False),
    sa.Column('EFFECTIVE_START_DATE', sa.Date(), nullable=False),
    sa.Column('EFFECTIVE_END_DATE', sa.Date(), nullable=False),
    sa.Column('FIRST_NAME', sa.String(length=150), nullable=False),
    sa.Column('MIDDLE_NAME', sa.String(length=150), nullable=True),
    sa.Column('LAST_NAME', sa.String(length=150), nullable=False),
    sa.Column('DATE_OF_BIRTH', sa.Date(), nullable=False),
    sa.Column('JOB_LOCATION', sa.String(length=150), nullable=True),
    sa.Column('WORKER_TYPE', sa.String(length=15), nullable=False),
    sa.Column('MOBILE_NO', sa.String(length=10), nullable=True),
    sa.Column('USER_ID', sa.String(length=30), nullable=True),
    sa.Column('EMAIL_ID', sa.String(length=150), nullable=True),
    sa.Column('CREATED_BY', sa.String(length=150), nullable=True),
    sa.Column('LAST_UPDATED_BY', sa.String(length=150), nullable=True),
    sa.Column('CREATION_DATE', sa.DateTime(), nullable=True),
    sa.Column('LAST_UPDATED_DATE', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['USER_ID'], ['admindetails.USER_ID'], ),
    sa.PrimaryKeyConstraint('EMPLOYEE_ID', 'EFFECTIVE_START_DATE', 'EFFECTIVE_END_DATE')
    )
    op.create_table('addressdetails',
    sa.Column('ADDRESS_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EMPLOYEE_ID', sa.Integer(), nullable=True),
    sa.Column('DATE_FROM', sa.Date(), nullable=False),
    sa.Column('DATE_TO', sa.Date(), nullable=False),
    sa.Column('ADDRESS_TYPE', sa.String(length=150), nullable=True),
    sa.Column('ADDRESS', sa.String(length=150), nullable=False),
    sa.Column('CITY', sa.String(length=150), nullable=False),
    sa.Column('STATE', sa.String(length=150), nullable=False),
    sa.Column('COUNTRY', sa.String(length=150), nullable=False),
    sa.Column('PIN_CODE', sa.String(length=15), nullable=False),
    sa.Column('CREATED_BY', sa.String(length=150), nullable=True),
    sa.Column('LAST_UPDATED_BY', sa.String(length=150), nullable=True),
    sa.Column('CREATION_DATE', sa.DateTime(), nullable=True),
    sa.Column('LAST_UPDATED_DATE', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['EMPLOYEE_ID'], ['employeedetails.EMPLOYEE_ID'], ),
    sa.PrimaryKeyConstraint('ADDRESS_ID', 'DATE_FROM', 'DATE_TO')
    )
    op.create_table('employementdetails',
    sa.Column('ASSIGNMENT_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EMPLOYEE_ID', sa.Integer(), nullable=True),
    sa.Column('EFFECTIVE_START_DATE', sa.Date(), nullable=False),
    sa.Column('EFFECTIVE_END_DATE', sa.Date(), nullable=False),
    sa.Column('DATE_OF_JOINING', sa.Date(), nullable=False),
    sa.Column('ORGANIZATION_NAME', sa.String(length=300), nullable=False),
    sa.Column('DESIGNATION', sa.String(length=400), nullable=False),
    sa.Column('DEPARTMENT', sa.String(length=400), nullable=True),
    sa.Column('PERSON_TYPE', sa.String(length=70), nullable=False),
    sa.Column('CONFIRMATION_DATE', sa.Date(), nullable=True),
    sa.Column('CTC', sa.Float(precision=2), nullable=False),
    sa.Column('STATUS', sa.String(length=40), nullable=True),
    sa.Column('PROBATION_PERIOD', sa.String(length=30), nullable=False),
    sa.Column('NOTICE_PERIOD', sa.String(length=30), nullable=True),
    sa.Column('CURRENT_COMPANY_EXPERIENCE', sa.String(length=30), nullable=True),
    sa.Column('PREVIOUS_EXPERIENCE', sa.String(length=30), nullable=True),
    sa.Column('TOTAL_EXPERIENCE', sa.String(length=30), nullable=True),
    sa.Column('PRE_ANNUAL_SALARY', sa.String(length=30), nullable=True),
    sa.Column('CREATED_BY', sa.String(length=300), nullable=True),
    sa.Column('LAST_UPDATED_BY', sa.String(length=300), nullable=True),
    sa.Column('CREATION_DATE', sa.DateTime(), nullable=True),
    sa.Column('LAST_UPDATED_DATE', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['EMPLOYEE_ID'], ['employeedetails.EMPLOYEE_ID'], ),
    sa.PrimaryKeyConstraint('ASSIGNMENT_ID', 'EFFECTIVE_START_DATE', 'EFFECTIVE_END_DATE')
    )
    op.create_table('letters',
    sa.Column('LETTER_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EMPLOYEE_ID', sa.Integer(), nullable=True),
    sa.Column('TEMPLATE_ID', sa.String(length=150), nullable=True),
    sa.Column('LETTER_SIZE', sa.Integer(), nullable=True),
    sa.Column('LETTER_NAME', sa.String(length=150), nullable=False),
    sa.Column('LETTER', sa.LargeBinary(length=20971520), nullable=True),
    sa.Column('LETTER_TYPE', sa.String(length=150), nullable=True),
    sa.Column('CREATED_BY', sa.String(length=150), nullable=True),
    sa.Column('LAST_UPDATED_BY', sa.String(length=150), nullable=True),
    sa.Column('CREATION_DATE', sa.DateTime(), nullable=True),
    sa.Column('LAST_UPDATED_DATE', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['EMPLOYEE_ID'], ['employeedetails.EMPLOYEE_ID'], ),
    sa.ForeignKeyConstraint(['TEMPLATE_ID'], ['templates.TEMPLATE_ID'], ),
    sa.PrimaryKeyConstraint('LETTER_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('letters')
    op.drop_table('employementdetails')
    op.drop_table('addressdetails')
    op.drop_table('employeedetails')
    op.drop_table('templates')
    op.drop_table('admindetails')
    # ### end Alembic commands ###
